### ISSUE TITLE
无法使用移除操作

### ISSUE THREAD

**Issue by gnilix** [Eugeoter/sd-dataset-manager#2]
The project is very practical, thank you.
BUT after the update, I encountered such a problem: an error occurs when using the “Remove” button, the console information is as follows:
项目非常实用，感谢。
但是当我更新后出现了这样的问题：使用“移除”按钮时报错，控制台信息如下：
remove tags batch processing:   0%|                         | 0/1556 [21:41<?, ?steps/s]
remove tags batch processing:   0%|                         | 0/1556 [00:00<?, ?steps/s]Traceback (most recent call last):
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\56247\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "D:\dataset-manager\sd-dataset-manager\waifuset\ui\ui.py", line 1335, in wrapper
    results.extend(edit(batch, *args, **kwargs))
  File "D:\dataset-manager\sd-dataset-manager\waifuset\utils\log_utils.py", line 9, in inner
    res = func(*args, **kwargs)
  File "D:\dataset-manager\sd-dataset-manager\waifuset\ui\ui.py", line 1315, in edit
    new_img_info = func(img_info.copy(), *args, **extra_kwargs, **kwargs)
TypeError: create_ui.<locals>.remove_tags() missing 1 required positional argument: 'regex'

**Comment by Eugeoter** [comment]
很抱歉带来不便。我已经在新的版本更新中修复了此bug。
使用git pull即可更新
